kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: governance-policy-status-sync
subjects:
- kind: ServiceAccount
  name: governance-policy-status-sync
  namespace: open-cluster-management-agent-addon
roleRef:
  kind: ClusterRole
  name: governance-policy-status-sync
  apiGroup: rbac.authorization.k8s.io
