# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

# list of Resource Config to be Applied
resources:
  - ./yamls/operator.yaml
  - ./yamls/clusterrole.yaml
  - ./yamls/clusterrole_binding.yaml
  - ./yamls/role.yaml
  - ./yamls/role_binding.yaml
  - ./yamls/service_account.yaml
                             
patchesJson6902:
  - path: operator.json
    target:
      group: apps
      version: v1
      kind: Deployment
      name: governance-policy-status-sync