kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: governance-policy-template-sync
subjects:
- kind: ServiceAccount
  name: governance-policy-template-sync
  namespace: multicluster-endpoint
roleRef:
  kind: ClusterRole
  name: governance-policy-template-sync
  apiGroup: rbac.authorization.k8s.io
