kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: governance-policy-template-sync
rules:
- apiGroups:
  - "policies.open-cluster-management.io"
  - "policies.ibm.com"
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch