kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: governance-policy-propagator-global
subjects:
- kind: ServiceAccount
  name: governance-policy-propagator
  namespace: open-cluster-management
roleRef:
  kind: ClusterRole
  name: governance-policy-propagator
  apiGroup: rbac.authorization.k8s.io
