kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: governance-policy-propagator
subjects:
- kind: ServiceAccount
  name: governance-policy-propagator
roleRef:
  kind: Role
  name: governance-policy-propagator
  apiGroup: rbac.authorization.k8s.io
