apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam-policy-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: iam-policy-controller
  template:
    metadata:
      labels:
        name: iam-policy-controller
    spec:
      serviceAccountName: iam-policy-controller
      imagePullSecrets:
        - name: multiclusterhub-operator-pull-secret
      containers:
        - name: iam-policy-controller
          imagePullPolicy: Always
          image: quay.io/open-cluster-management/iam-policy-controller:latest-dev
          args:
            - '--v=0'
            - '--update-frequency=10'
            - '--watch-ns=managed'
