apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: certificatepolicies.policies.open-cluster-management.io
spec:
  group: policies.open-cluster-management.io
  names:
    kind: CertificatePolicy
    plural: certificatepolicies
    shortNames:
    - certpl
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            labelSelector:
              type: object
            minimumDuration:
              description: Minimum duration before a certificate expires that it is
                considered non-compliant. Golang's time units only
              type: string
            namespaceSelector:
              description: selecting a list of namespaces where the policy applies
              properties:
                exclude:
                  items:
                    type: string
                  type: array
                include:
                  items:
                    type: string
                  type: array
              type: object
            remediationAction:
              description: enforce, inform
              type: string
            severity:
              description: low, medium, or high
              type: string
          type: object
        status:
          properties:
            compliancyDetails:
              description: Compliant, NonCompliant, UnkownCompliancy
              type: object
            compliant:
              type: string
          type: object
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
